CREATE TABLE job_sites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL REFERENCES app_users(id),
    site_id BIGINT NOT NULL REFERENCES job_sites(id),
    work_date DATE NOT NULL,
    submitted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    notes VARCHAR(4000) NOT NULL,
    hard_hat VARCHAR(10) NOT NULL CHECK (hard_hat IN ('PASS','ISSUE','NA')),
    high_visibility_vest VARCHAR(10) NOT NULL CHECK (high_visibility_vest IN ('PASS','ISSUE','NA')),
    safety_boots VARCHAR(10) NOT NULL CHECK (safety_boots IN ('PASS','ISSUE','NA')),
    eye_protection VARCHAR(10) NOT NULL CHECK (eye_protection IN ('PASS','ISSUE','NA')),
    fall_protection VARCHAR(10) NOT NULL CHECK (fall_protection IN ('PASS','ISSUE','NA')),
    ladders_scaffolds VARCHAR(10) NOT NULL CHECK (ladders_scaffolds IN ('PASS','ISSUE','NA')),
    tools_cords VARCHAR(10) NOT NULL CHECK (tools_cords IN ('PASS','ISSUE','NA')),
    hazards_controlled VARCHAR(10) NOT NULL CHECK (hazards_controlled IN ('PASS','ISSUE','NA')),
    CONSTRAINT uq_worker_site_date UNIQUE (worker_id,site_id,work_date)
);
CREATE INDEX ix_submissions_work_date ON submissions(work_date DESC,id DESC);
CREATE TABLE photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL REFERENCES submissions(id),
    storage_key VARCHAR(255) NOT NULL UNIQUE,
    content_type VARCHAR(50) NOT NULL CHECK (content_type IN ('image/jpeg','image/png')),
    byte_size BIGINT NOT NULL CHECK (byte_size > 0 AND byte_size <= 5000000)
);
CREATE INDEX ix_photos_submission ON photos(submission_id);
